
services:
  elasticsearch:
    image: elasticsearch:8.13.0
    container_name: monitoring-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elk
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: kibana:8.13.0
    container_name: monitoring-kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  logstash:
    image: logstash:8.13.0
    container_name: monitoring-logstash
    volumes:
      - ./logstash-pipeline:/usr/share/logstash/pipeline
      - ./sample-logs:/usr/share/logstash/sample-logs
    ports:
      - "6000:6000"
      - "9600:9600"
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - elk
    environment:
      - "LS_JAVA_OPTS=-Xmx256m -Xms256m"

networks:
  elk:
    driver: bridge

volumes:
  elasticsearch_data:
    driver: local
